#!/usr/bin/env bash
#
# This script is executed once on the initial run of the installation script. It installs things needed by our aliases.
#
# To force re-execution, use the --force flag. This would only ever be needed if this script has changed since you last ran the update script.

sudo easy_install -U Pygments

