#!/usr/bin/env bash

## Source: https://github.com/mathiasbynens/dotfiles/blob/master/bootstrap.sh

## Read user input, taking the first character that was entered (-n 1)
read -p "This may overwrite existing files in your home directory. Are you sure? (y/n) " -n 1;
echo "";

if [[ $REPLY =~ ^[Yy]$ ]]; then
  rsync --exclude ".git/" \
    --exclude ".DS_Store" \
    --exclude ".osx" \
    --exclude "install" \
    --exclude "README.md" \
    --exclude "themes/" \
    -avh --no-perms -n . ~;
else
  echo "User cancelled installation. - :("
fi;
